In [9]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
n_trials =100_000

How likely is it that you roll doubles when rolling two dice?



In [17]:
#making list of two dice rolling at random 
outcome = [1,2,3,4,5,6]
n_dice = 2

In [18]:
rolls = np.random.choice(outcome, (n_trails,n_dice))
rolls 

array([[2, 1],
       [4, 4],
       [5, 4],
       ...,
       [5, 1],
       [1, 3],
       [1, 6]])

In [19]:
rolls[:,0]

array([2, 4, 5, ..., 5, 1, 1])

In [20]:
rolls[:,1]

array([1, 4, 4, ..., 1, 3, 6])

In [21]:
rolls[:,0] =rolls[:,1]

In [22]:
rolls.T

array([[1, 4, 4, ..., 1, 3, 6],
       [1, 4, 4, ..., 1, 3, 6]])

In [23]:
rolls.T[0]

array([1, 4, 4, ..., 1, 3, 6])

In [24]:
rolls.T[1]

array([1, 4, 4, ..., 1, 3, 6])

In [25]:
doubles = rolls[:,0] == rolls[:,1] 
doubles


array([ True,  True,  True, ...,  True,  True,  True])

In [26]:
doubles.sum()


100000

In [28]:
n_trials

100000

In [30]:
len(doubles)

100000

In [29]:
doubles.sum() / len(doubles)

1.0

In [31]:
doubles.mean()

1.0

If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [14]:
outcome = ['h','t']

n_coins = 8

In [15]:
flips = np.random.choice(outcome, (n_trials, n_coins))
flips

array([['h', 't', 'h', ..., 't', 't', 't'],
       ['t', 'h', 'h', ..., 't', 't', 't'],
       ['h', 'h', 'h', ..., 'h', 'h', 'h'],
       ...,
       ['h', 'h', 't', ..., 't', 'h', 'h'],
       ['t', 't', 't', ..., 't', 'h', 'h'],
       ['t', 'h', 'h', ..., 't', 'h', 't']], dtype='<U1')

In [16]:
heads = (flips == 'h').sum(axis=1)
heads


array([3, 2, 7, ..., 6, 4, 4])

In [17]:
(heads == 3).mean()

0.2188

In [18]:
(heads > 3).mean()

0.63727

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [19]:
outcome = ['ds', 'wd', 'wd','wd']
n_billboard = 2 

In [20]:
billboards = np.random.choice(outcome, (n_trails,n_billboard))
billboards

array([['wd', 'wd'],
       ['ds', 'wd'],
       ['wd', 'wd'],
       ...,
       ['ds', 'wd'],
       ['wd', 'wd'],
       ['ds', 'wd']], dtype='<U2')

In [22]:
ds_billboard = (billboards == 'ds').sum(axis=1)
ds_billboard

array([0, 1, 0, ..., 1, 0, 1])

In [23]:
(ds_billboard == 2).mean()

0.06289

Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values



In [24]:
μ = 3.0
σ = 1.5
n_days = 5 
poptart_dist = stats.norm(μ, σ)

In [26]:
daily = np.random.normal(loc=3, scale=1.5, size=(n_trials,n_days))
daily

array([[2.20619509, 2.0612249 , 3.61737208, 2.60321849, 2.33879744],
       [1.31504119, 4.51033193, 7.55085426, 2.38101693, 5.12712882],
       [3.89548493, 3.65387867, 4.46084158, 3.05793858, 1.93036442],
       ...,
       [0.36136288, 2.60858614, 3.30771474, 5.17043941, 3.34148376],
       [2.32721383, 2.09287431, 4.99849755, 4.33008179, 3.84431963],
       [2.07311417, 1.99719382, 1.13492724, 2.26643432, 3.30817952]])

In [27]:
weekly = daily.sum(axis=1)
weekly

array([12.82680801, 20.88437313, 16.99850818, ..., 14.78958693,
       17.59298711, 10.77984907])

In [28]:
(17 - weekly > 1).mean()

0.61656

In [29]:
((17 - weekly) >= 1).mean()

0.61656

Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.

Women have a mean of 170, sd = 6cm.

Since you have means and standard deviations, you can use np.random.normal to generate observations.

If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [42]:
mean_men = 178
sd_men = 8


mean_women = 170
sd_women = 6

In [43]:
n_trials = 10_000

In [47]:
height_men = np.random.normal(mean_men,sd_men,n_trials)
height_men

array([175.93885746, 174.61677551, 175.75437261, ..., 188.38556339,
       167.25597189, 186.24407198])

In [48]:
heights_women = np.random.normal(mean_women, sd_women, n_trials)
heights_women

array([181.01780569, 168.9845852 , 169.74231719, ..., 172.8660817 ,
       169.09357649, 162.00955799])

In [50]:
(heights_women > height_men).mean()

0.2027

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

In [51]:
outcomes = ['p','f']
probs_outcomes = [249/250, 1/250]
n_students = 50

In [52]:
installs = np.random.choice(outcomes, (n_trials, n_students),
                p=probs_outcomes)
installs


array([['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ...,
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p']], dtype='<U1')

In [53]:
total_fails = (installs == 'f').sum(axis=1)
total_fails


array([1, 0, 0, ..., 0, 0, 0])

In [54]:
(total_fails == 0).mean()


0.8153

In [55]:
n_students = 100

installs = np.random.choice(outcomes, (n_trials, n_students),
                p=probs_outcomes)
total_fails = (installs == 'f').sum(axis=1)

(total_fails == 0).mean()

0.6651

In [56]:
n_students = 150

installs = np.random.choice(outcomes, (n_trials, n_students),
                p=probs_outcomes)
total_fails = (installs == 'f').sum(axis=1)

(total_fails > 0).mean()

0.4592

In [57]:
n_students = 450

installs = np.random.choice(outcomes, (n_trials, n_students),
                p=probs_outcomes)
total_fails = (installs == 'f').sum(axis=1)

(total_fails == 0).mean()


0.1656

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

In [58]:
p_truck = 0.7
n_days = 3

In [59]:
is_truck_question = np.random.random((n_trials, n_days))
is_truck_question

array([[0.19651258, 0.98129325, 0.55568014],
       [0.50614104, 0.41748362, 0.29270759],
       [0.1958571 , 0.00689099, 0.27673156],
       ...,
       [0.49189427, 0.84503755, 0.14221551],
       [0.63321952, 0.7973471 , 0.35218494],
       [0.92450561, 0.26600147, 0.67478758]])

In [60]:
yes_truck = is_truck_question < p_truck
yes_truck

array([[ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       ...,
       [ True, False,  True],
       [ True, False,  True],
       [False,  True,  True]])

In [61]:
(yes_truck.sum(axis=1) == 0).mean()

0.0254

In [70]:
n_days = 5

In [71]:
is_truck_question = np.random.random((n_trials, n_days))

yes_truck = is_truck_question < p_truck

(yes_truck.sum(axis=1) >= 1).mean()

0.9965

If 23 people are in the same room, what are the odds that two of them share a birthday? 
What if it's 20 people? 40?

50.73%

In [72]:
n_people = 23
outcomes = list(range(1,366))

In [73]:
birthdays = np.random.choice(outcomes, (n_trials, n_people))
birthdays

array([[ 87,  46, 183, ..., 212, 174, 104],
       [215,  97, 251, ..., 345, 117, 203],
       [134,  56,  70, ...,  80, 166, 279],
       ...,
       [162, 140,  25, ..., 157, 321, 123],
       [182, 158, 338, ...,  10, 213, 285],
       [ 91, 155, 270, ...,  90,  53, 277]])

In [74]:
birthdays = pd.DataFrame(birthdays)
birthdays.head()

0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0   87   46  183   87  350   88  206  275  351   72  ...  172  153    3  258   
1  215   97  251  120  229  188   18   23  183  119  ...   49  304  227   52   
2  134   56   70   19  283  182   58   51  115  330  ...   99  344  112   58   
3  238  141   80  365  204  346  200   65  180  190  ...   69    2  281  160   
4  202    7   45  205   91  256   38  206  216  273  ...   98  303  170  197   

    17   18   19   20   21   22  
0  327  170  198  212  174  104  
1  342   78   76  345  117  203  
2  116   82  208   80  166  279  
3  349  185  120   67  139  237  
4  258  212  209  119  324  149  

[5 rows x 23 columns]

In [75]:
birthdays.nunique(axis=1)

0       22
1       23
2       22
3       23
4       23
        ..
9995    22
9996    23
9997    22
9998    23
9999    22
Length: 10000, dtype: int64

In [76]:
(birthdays.nunique(axis=1) < n_people).mean()

0.5095

In [77]:
n_people = 20

birthdays = np.random.choice(outcomes, (n_trials, n_people))
birthdays = pd.DataFrame(birthdays)

(birthdays.nunique(axis=1) < n_people).mean()

0.4095

In [78]:
n_people = 40

birthdays = np.random.choice(outcomes, (n_trials, n_people))
birthdays = pd.DataFrame(birthdays)

(birthdays.nunique(axis=1) < n_people).mean()

0.8887